# Generated by Django 4.1 on 2022-08-28 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0002_rename_libros_libro_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='libros', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
